name: money_tracker_app
description: A Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  calendar_date_picker2: ^1.0.1
  easy_rich_text: ^2.1.0
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.4
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.5
  flutter_time_picker_spinner: ^2.0.0
  flutter_web_plugins:
    sdk: flutter
  function_tree: ^0.9.0
  go_router: ^14.0.2
  intl: ^0.18.0
  realm: ^2.2.1
  reorderables: ^0.6.0
  ##table_calendar: ^3.0.9
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.3.3
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svg/activity/
    - assets/svg/app/
    - assets/svg/building/
    - assets/svg/business/
    - assets/svg/emoji/
    - assets/svg/food/
    - assets/svg/game/
    - assets/svg/health/
    - assets/svg/household/
    - assets/svg/money/

  fonts:
    - family: WixMadeforDisplay
      fonts:
        - asset: assets/fonts/WixMadeforDisplay-Regular.ttf
        - asset: assets/fonts/WixMadeforDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/WixMadeforDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WixMadeforDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/WixMadeforDisplay-ExtraBold.ttf
          weight: 900
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf